name: dynapin
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - ipykernel
  - jupyter
  - dockq
  - dssp=3.1.4
  - ipywidgets
  - matplotlib
  - seaborn
  - moviepy
  - jsonpickle
  - python-kaleido
  - mdanalysis
  - pdbfixer
  - pdb-tools
  - freesasa
  - nglview=3.1.4
  - pip:
      - -e ./interfacea
      - -e .
